### ISSUE TITLE
Checklist for 4.1 release

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy#10390]
This is a checklist for the 4.1 release. The steps mentioned below are the ones in the [release guidelines](https://docs.astropy.org/en/latest/development/releasing.html)

### 4.1rc1

* [x] Backport all relevant PRs to v4.0.x and v4.1.x
* [x] Finalize 'What's new', ``.mailmap`` and ``docs/credits.rst`` (done in https://github.com/astropy/astropy/pull/10370) [steps 3 & 4]
* [x] Update IERS tables (done in https://github.com/astropy/astropy/pull/10376) [step 5 in  [release guidelines](https://docs.astropy.org/en/stable/development/releasing.html)]
* [x] Resolve IERS issues in https://github.com/astropy/astropy/pull/10387
* [x] Backport https://github.com/astropy/astropy/pull/10387 to 4.1.x branch (and 4.0.x if necessary?)
* [x] Build sdist and push ``v4.1rc1`` tag to GitHub [steps 6 to 17]
* [x] Update https://github.com/MacPython/astropy-wheels/pull/63 to point to the ``v4.1rc1`` tag [step 18 and 19]
* [x] Once the wheel PR passes, merge the PR, then download and publish wheels [step 21]
* [x] Re-build and publish source release [steps 22 and 23]
* [x] Build v4.1rc1 tag on RTD
* [x] Set up wiki page [as described [here](https://docs.astropy.org/en/latest/development/releasing.html#modifications-for-a-beta-release-candidate-release)]: [link to wiki page](https://github.com/astropy/astropy/wiki/astropy-v4.1-release-candidate-(RC)-Testing)
* [x] Announce 4.1rc1 to astropy-dev

### 4.1rc?

* [x] Optionally do more RCs!

### 4.1 (final)

* [x] Backport any fixes to v4.0.x and do v4.0.2 release (so that changelog doesn't have an unreleased version in v4.1)
* [x] Backport any additional fixes to v4.1.x
* [x] Update number of contributors and PRs in what's new (see [here](https://github.com/astropy/astropy/pull/10377) for how this is done now)
* [x] Go through main release steps
* [ ] Update RTD and website (with announcement)
* [ ] Announce!

**Comment by pllim** [comment]
If it is decided that #10398 should go in 4.1, I think it needs to be added to **4.1rc** checklist.

**Comment by pllim** [comment]
I think at least RC2 needs to happen to test #10400 .
