### ISSUE TITLE
TST: Unpin pytest when pytest-doctestplus 0.8 is released

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#10612]
### Description

CI is breaking bad. (Get the TV show reference? 😉 😉 )

### Expected behavior

CI to pass when there is nothing wrong with the relevant code (in PR or `master`).

### Actual behavior

Breaking bad.

### Steps to fix

- [x] Pin to `pytest<6` in astropy/ci-helpers#453 .
- [x] Fix doctest errors caused by `pandas` (#10608), see proposed patch at #10609 .
- [x] Fix astropy/pytest-doctestplus#118 (fixed by astropy/pytest-doctestplus#120, thanks to @saimn ).
- [x] Release a new version of `pytest-doctestplus`.
- [x] Undo the pin; i.e., revert astropy/ci-helpers#453, see astropy/ci-helpers#455

**Comment by pllim** [comment]
Nothing else we can do here. astropy/ci-helpers#455 should resolve this.
