### ISSUE TITLE
Changelog: A New Hope (with Towncrier)

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#11351]
This is a meta issue to keep track of our change log transition process. Also see https://github.com/astropy/astropy/pull/11279#issuecomment-786126572

# Before 4.2.1 release (i.e., as soon as possible)

- [x] @saimn to draft a memo about the changelog transition that is going to happen.
- [x] @pllim to send it out to relevant communication channels (astropy-dev, Slack #general) 
  - https://groups.google.com/g/astropy-dev/c/-D05W4C7y8I
  - https://astropy.slack.com/archives/C067V74GK/p1614613870018000
- [x] @Cadair to push bot changes (using `baldrick` to check new change log and disable checking on `astropy-bot` side) to #11279
- [x] @saimn and/or @Cadair to decide whether we should go with [SunPy Sphinx extension](https://github.com/sunpy/sunpy/blob/master/sunpy/util/sphinx/changelog.py) or [sphinxcontrib-towncrier](https://github.com/sphinx-contrib/sphinxcontrib-towncrier) -- Decision was to use [OpenAstronomy/sphinx-changelog](https://github.com/OpenAstronomy/sphinx-changelog) ported from SunPy
- [x] Depending on decision above, @Cadair to move [SunPy Sphinx extension](https://github.com/sunpy/sunpy/blob/master/sunpy/util/sphinx/changelog.py) to OpenAstronomy GitHub org. -- Done at [OpenAstronomy/sphinx-changelog](https://github.com/OpenAstronomy/sphinx-changelog)
- [x] @saimn to have #11279 ready for merge by wrapping it up; i.e., having a minimally viable dev docs and including Sphinx extension of choice from above.

# Right after 4.2.1 release

- [x] We merge #11279 (that closes out #10334)
- [x] @astrofrog or @eteq to backport PRs currently merged in `master` to the affected branches: `4.2.x` and `4.0.x`
- [x] @saimn to use Tom A's magical script to port existing change log format into "fragments" for affected branches: `master`, `4.2.x`, and `4.0.x`. It is important to get the PRs currently merged in `master` to be backported **before** doing the transition (see above).
- [x] Another memo to astropy-dev (https://groups.google.com/g/astropy-dev/c/-D05W4C7y8I) and Slack about this.

# Before 4.3 release

- [x] TBD devs to open necessary follow-up PRs to polish contributing guidelines, dev and release docs to reflect the changes to change log. -- This will be handled in a as-needed basis. Basic doc is already in.

**Comment by taldcroft** [comment]
> Tom's magical script

Haha. At least some good has come from the work on the YAML option. In the end I'm glad a better way forward was found, thanks all for getting this organized!

**Comment by pllim** [comment]
@saimn said this is resolved. 🎉  Thank you, everyone involved!
