### ISSUE TITLE
Documentation reorganization

### ISSUE THREAD

**Issue by embray** [astropy/astropy#11620]
This issue is to discuss a number of issues related to reorganization of the Astropy documentation as well as themeing.

* [x] There has been some discussion between @adrn and I, as well as on Slack, about possibly adopting the [pydata-sphinx-theme](https://github.com/pydata/pydata-sphinx-theme) for Astropy.  It is now used by NumPy, SciPy, Pandas, and several others in the "PyData" ecosystem.  Of course, we would probably like to tweak the theme a bit to keep Astropy's styling (e.g. I would like to keep the existing color scheme, with a dark nav bar, etc.).  This is also discussed in #11520 and @tupui has offered to help.
  * [x] @pllim also requested a "dark mode" which would be nice, but I think that's a feature that should be added directly to pydata-sphinx-theme if at all.

* [x] Adapting the pydata-sphinx-theme is also a good opportunity to redo the top navigation bar a bit.  #8320 relates to this insofar as using the nav bar from astropy.org.  For the documentation I'm not sure using it exactly as-is is necessarily what we want (e.g. having the "Documentation" menu on the docs themselves would be redundant.  But keeping links like "About" and "Affiliated Packages" might be good.

* [ ] The NumPy, SciPy, and Pandas docs all have an "API reference" link on their nav bars.  Astropy doesn't currently have a top-level API reference page.  Rather, most of the existing documentation pages are thematic by sub-package.  They contain some narrative documentation about the sub-package, and typically have some API reference at the bottom.  I think we should keep this format, though it would also be nice to have a single index of all API docs for all sub-packages, ordered alphabetically.  I have often wanted this myself, as a quick way to find API docs for a specific package, rather than having to scroll through all the narrative docs to find the API reference for that package.  See also #9277

* [x] Add a top-level page for the development docs.  Improving the development docs is actually the issue that originally prompted this discussion. In short, rather than having an index of the development docs directly on the main documentation index as we have currently (see https://docs.astropy.org/en/v4.2/#developer-documentation) it would be good to have a top-level development page featuring a sort of "quick start" guide at the top-level, followed by a table of contents for more detailed pages.  This aspect is tracked in more detail at #11621.

All of the above issues are intertwined on some level.

**Comment by pllim** [comment]
Revisiting in 2024, I think only #9277 is left and that is already a separate issue, so closing this.
