### ISSUE TITLE
Release final 0.4.0 version

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy#1802]
This is an issue to keep track of critical tasks for the 0.4.0 release. The following is a list based on discussions at the coordination meeting along with whoever is responsible for these.

**Integration of units:**
- [ ] Improve integration of Table columns and quantities (#664, #1762; possible implementation in #1839) - @astrofrog @taldcroft @embray @mhvk
- [ ] Improve integration of Table columns with Time and Coordinate objects (#664; sample implementations #1833 and #1835) - @taldcroft @mhvk 
- [ ] Implement masked quantities (#1852) - @adrn @mhvk 

**Infrastructure and code:**
- [x] Revamp configuration system (#1555) - @mdboom @eteq
- [x] Create and use `astropy_helpers` package for common infrastructure code to Astropy and affiliated packages (#1563) - @astrofrog @embray
- [x] Make all of Astropy six-compatible - @mdboom

**New sub-packages:**
- [x] SAMPy as `astropy.vo.samp` (#972) - @lpaioro @cdeil @astrofrog

**Coordinates, Time, and Observatories:**
- [x] implement sidereal time (#1418) @mhvk
- [x] re-design lower-level classes for coordinates (#1550, #1553) @eteq @adrn @astrofrog 
- [x] create `SkyCoordinates` high-level class (#1589) @taldcroft @eteq @astrofrog
- [x] `EarthLocation` class, list of observatories, and plug that into sidereal times (#1928) @eteq @mhvk
- [ ] fully implement IAU 2000 trasnformation stack for ICRS -> AltAz @eteq @mhvk
- [ ] automate `IERS` updates (#1697) and other data with expiration dates. @mhvk @taldcroft @eteq
- [ ] barycentric coordinates and velocities, ideally at VLBI precision (if things go quickly enough)

**Stabilize modeling API:**
- [ ] ~~implement support for Quantities(#1464) @nden @embray @wkerzendorf~~
- [ ] ~~implement composite models (including fitting) (#1054) @nden @embray @wkerzendorf~~
- [x] separate optimization from statistic in fitters @nden @embray @wkerzendorf 
- [ ] ~~implement custom_model_2d (#1763) @embray~~ 
- [ ] ~~add 'default_fitter', 'last_fitter' and 'fit' method to models (#1330, #979) @nden @embray @wkerzendorf~~ 
- [ ] ~~add support for getting uncertainties on parameters (#1827)~~

**Miscellaneous:**
- [ ] Implement any backward-incompatible API changes needed for the future generalized WCS (even if the full thing isn't implemented) - @nden @perrygreenfield @jehturner

In addition, the following documentation/help-related issues should be addressed:
- [ ] Implement a help system tied to exceptions/warnings - @demetri
- [x] Get tutorials/blog posts going - @kelle @jfoster17 @adrn @migueldvb

Lower priority issues
- [ ] Better integration of FITS tables and VO tables with the Table class - @mdboom @taldcroft @embray
