### ISSUE TITLE
What's new for 1.0

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy#2935]
Just to remind ourselves of entries to add:

* [x] Fast ascii.io reader/writer [#2716] - @taldcroft
* [x] Summary of `modeling` package updates [#2580, #2835, ...] [owner: @embray]
* [x] Visualization sub-package @astrofrog
* [x] Analytic functions @pllim
* [x] AltAz conversions @eteq
* [x] Mixin columns [#3011] - @taldcroft
* [x] LTS release @astrofrog or @eteq
* [x] Major API changes?
* [x] Dropped support for Numpy 1.5 [#3100]
* [x] Galactocentric frame @adrn [#3351]

**Comment by astrofrog** [comment]
@taldcroft @embray @eteq - just for info you are all marked above as being responsible for writing a section in the what's new for 1.0. If possible, it would be great to have these done by the end of the week since the RC deadline is coming up.

**Comment by astrofrog** [comment]
I have added headings for the sections in e59504c819bae2abb1026923ba095f59868895be so that we can all work on this at once without danger of rebasing. Please don't change the order of the sections for now, though you can change the titles for your sections.

**Comment by adrn** [comment]
Maybe I should add something on the `Galactocentric` frame?

**Comment by astrofrog** [comment]
@adrn - indeed, that would be great! I've added a heading in 1377218cf296bd9826a413f34347a6868c87bba9 and a to-do item above. We should have all these sections written this week ideally.

**Comment by taldcroft** [comment]
Sorry, a little late here, but I'll try to do this tomorrow.  Assuming it gets merged, will APE-6 and ECSV make the What's New?

**Comment by astrofrog** [comment]
@taldcroft - if APE6 and ECSV get merged, they *should* be included in the 'What's new?'! Unless you want to keep it low-key initially and let more advanced users discover it until the format is stable of course.

**Comment by taldcroft** [comment]
@astrofrog - I want to shout about it if anyone will listen.

**Comment by astrofrog** [comment]
@taldcroft - can you open a PR for the ECSV what's new?

**Comment by taldcroft** [comment]
@astrofrog - will do.

**Comment by astrofrog** [comment]
I just added a note about using the changelog for API changes in https://github.com/astropy/astropy/pull/3451, I don't think we need to detail them in the 'what's new'.

So this is closed by https://github.com/astropy/astropy/pull/3451

**Comment by eteq** [comment]
Oops, this should have been closed when #3451 was closed.  Closing it now.

**Comment by embray** [comment]
Hooray.
