### ISSUE TITLE
Release final v1.2

### ISSUE THREAD

**Issue by eteq** [astropy/astropy#4395]
[edited by @astrofrog @taldcroft]

There was a list of issues in this issue that had been copied over from the 1.1 issue (#3519) but which also diverged from what we did for 1.2 in the end, so I've moved that to the wiki: https://github.com/astropy/astropy/wiki/Old-to-do-list-for-1.1

Instead, here are some feature pull requests that we might want to exceptionally consider backporting to the 1.2.x branch before the release (these should be considered by the coordination committee):

* [x] Refinements/API changes for `AstrometricFrame` - #4941
* [x] Example Gallery improvements - #4924
* [x] Support for choosing different sources for planet positions - https://github.com/astropy/astropy/pull/4920 - @mhvk @StuartLittlefair @eteq
* [x] #4952 - this is a bug fix (there are other bug fixes *not* in this list because they are included by default), but is noted here because it is important for #4920 to actually get the right answers for some items.  Note that #4979 needs to be backported *first* before #4952 (it was originally one issue, but it turns out the changes in #4979 need to go to 1.0.x too, while the changes merged in #4952 are 1.2.x, so it was split into two issues)
* [x] Auto-downloading of IERS-A data - https://github.com/astropy/astropy/pull/4436 - @taldcroft @mhvk @eteq

Other to-dos for the release:

* [x] Release and update astropy-helpers in astropy and package-template if needed
* [x] Write 'what's new in 1.2'
* [x] Do a v1.0.x release
* [x] Clean up changelog - @astrofrog
* [x] Update IERS B file (#4994)
* [x] Backport any PRs milestoned as v1.2.0 merged after the feature freeze (mostly bug and documentation fixes, and maybe a couple of feature PRs from the list above)
* [x] Update list of contributors
* [x] Update stats on contributions in 'What's new'
* [ ] Update release tooling/instructions for latest procedures

One question is, do we actually bother doing another bugfix release in the v1.1.x branch, or do we just move those changelog entries to v1.2.0?

**Comment by taldcroft** [comment]
Auto-downloading of IERS-A data #4436 is merged to master now.

**Comment by astrofrog** [comment]
@taldcroft - isn't #4930 just a bug fix? (if so it doesn't need to be in the above list since it should be uncontroversially backported)

**Comment by taldcroft** [comment]
@astrofrog - yes, you are correct, I have taken it out of the issue description above.  It is merged now to master and milestoned for 1.0.10.

**Comment by eteq** [comment]
What's the "Do an LTS release" release about, @taldcroft and @astrofrog ? (Or did I write that?  I'm not sure since it's been edited...)

**Comment by astrofrog** [comment]
@eteq - I updated the whole block of text and I don't think there's anything left from what you had (now in the wiki page). I thought it would probably make sense to do a new 1.0.x release at the same time as (or a bit before) 1.2.0?

**Comment by astrofrog** [comment]
@eteq - I unticked the PRs you marked since we should only tick these once we've considered whether to backport them.

**Comment by eteq** [comment]
Ohh, gotch @astrofrog - I was thinking  #4436 was merged before the new release, but I now see it wasn't.

**Comment by astrofrog** [comment]
@mhvk - I'm having issues backporting https://github.com/astropy/astropy/pull/4770 to v1.0.x because, while it backports without conflicts, the tests don't pass afterwards. Since you are familiar with the units code (and this PR was from you), would you be happy to try and figure out what else needs to be backported for this to work?

**Comment by eteq** [comment]
Coordination committee agreed #4436 was a good backport to do because it was basically done before the freeze, just needed some rebase/cleanup (and is important to get in!)

**Comment by mhvk** [comment]
@astrofrog - happy to help in principle, but I don't really know how to try things out myself. Do many tests fail, or just the ones added by 4770?

**Comment by mhvk** [comment]
Could we add #4933 to the list? It updates IERS B to the latest version and also makes a correction to the `IERSAuto` code that came up when we did that.

**Comment by astrofrog** [comment]
@mhvk - testing that locally is pretty easy - just fetch the latest upstream, then do:

```shell
git checkout upstream/v1.0.x
git cherry-pick -m 1 4c6c904efb9ea948a8f019b305c06bac05c82257
```

Then run the tests. I can't remember exactly what test failed. Typically with this kind of issue, it means that there are other changes that we should be backporting that weren't milestoned as ``v1.0.x``. Alternatively, it could be the #4770 works properly only if we backported new features, in which case we should not backport #4770.

If you figure it out, don't push to v1.0.x yet - post your finding here and we can decide on the best way to proceed.

**Comment by mhvk** [comment]
That gives conflicts...  I'm running out of time here, so will focus on #4933 first.

**Comment by astrofrog** [comment]
@mhvk - ah yes it does give a minor conflict in ``quantity.py``. That to me suggests we're missing some previous commits that would need to also be backported for this to work. Once #4933 is done, it would be great if you could take a look.

**Comment by mhvk** [comment]
OK, I see what the problem is: in 1.0, we still supported tuples for powers, and this commit breaks it. Frankly, given how small of a problem this solved, I'd argue for just not backporting.

**Comment by astrofrog** [comment]
@mhvk - ok that sounds good, let's re-milestone to 1.2 (since there won't be another 1.1.x release)

**Comment by mhvk** [comment]
I merged #4933, the update to IERS B. I think this should be uncontroversial to still include in v1.2.0. As part of it, there was also a small bugfix to #4436.

**Comment by eteq** [comment]
I agree that #4933 is reasonable to backport to 1.2

**Comment by taldcroft** [comment]
Agreed on #4933.  This is actually fairly necessary since without it, tests will not pass when IERS-B is updated as it should normally be during the release process.

**Comment by eteq** [comment]
Oh, ok, then it's a bugfix (even if it's only an "at release" bug) and I'll go ahead and backport it now.

**Comment by mhvk** [comment]
Just thought I'd also point out #4952. This is nominally for `get_sun`, but it seems it may have exposed some larger bugs in the coordinate transforms. My sense is that we should get this in before releasing 1.2.

**Comment by eteq** [comment]
#4924 - not sure if this is a "doc fix" vs feature, but pretty straightforward, so @taldcroft @astrofrog, are you happy with backporting that?

**Comment by taldcroft** [comment]
:+1: on #4924.

**Comment by eteq** [comment]
#4952 and the related #4979 are in master.  Both should be backported (bug fixes), but they require some care in ordering - I've added a note in this issue's description detailing more.

(also, @astrofrog, waiting on your vote for #4924 before adding it to the list).

**Comment by eteq** [comment]
@astrofrog, @taldcroft, and/or @kelle - do you agree #4941 should also get backported (it's not in master yet, but probably will be within a day or two)? I think it should, as it's a fairly major API change to `AstrometricFrame`, which is new in 1.2...

**Comment by taldcroft** [comment]
Definitely :+1: on #4941.

**Comment by kelle** [comment]
abstain.

On Thu, May 26, 2016 at 11:40 AM, Tom Aldcroft <notifications@github.com>
wrote:

> Definitely 👍 on #4941 <https://github.com/astropy/astropy/pull/4941>.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/astropy/astropy/issues/4395#issuecomment-221909109>
>



-- 
Kelle Cruz, PhD — http://kellecruz.com/
917.725.1334 — Hunter: x16486 — AMNH: x3404

**Comment by astrofrog** [comment]
👍 for #4924 and #4941

**Comment by mhvk** [comment]
#4920 -- built-in ephemerides for solar-system bodies is now merged. This complements the JPL ephemeris work and provides a way to choose between the two. Note that there are some ordering requirements for the backport (see top of this issue).

**Comment by mhvk** [comment]
As the merger of #4979, I got a message that the backport of #4979 to 1.0.x led to a broken build. As I'm not sure who else gets these: see  https://travis-ci.org/astropy/astropy/builds/134155694

**Comment by astrofrog** [comment]
Just as an update, the backporting should be up-to-date as of today. The ``suggest_backports`` script incorrectly states that there are things that need to be backported, so don't trust it for now!

**Comment by astrofrog** [comment]
The backporting is once again up-to-date, and the CHANGES.rst file should be up-to-date in all branches

**Comment by astrofrog** [comment]
Again, we're up-to-date with backporting. I un-milestoned a few PRs that were not going to get included in 1.2, and the list is very manageable:

https://github.com/astropy/astropy/pulls?q=is%3Aopen+is%3Apr+milestone%3Av1.2.0

and we also need to make sure we look at these in case any should be included:

https://github.com/astropy/astropy/pulls?q=is%3Aopen+is%3Apr+milestone%3Av1.0.10

I am going to be offline for the next 2-3 days, so I would suggest that we try and get everything that needs to be merged merged in by Monday at the latest, and we start the process for the RC on Monday evening.

@eteq - if you have time before, you could already also start the process for the astropy-helpers RC, since that is ready to go?

**Comment by mwcraig** [comment]
I'm going to see if I can get a fix for this ready today (the fix could be merged after the RC, conceivably, but the bug is significant enough to warrant fixing in 1.2, I think): https://github.com/astropy/astropy/issues/4974

**Comment by eteq** [comment]
@mwcraig - any progress on the #4974 fix? (if it's almost there we could conceivably get that in before RC)

**Comment by mwcraig** [comment]
Close, I think...first fix I tried broke a few other things, working on it again now. Update in an hour.

**Comment by mwcraig** [comment]
@eteq  -- likely a little while longer...am tracing through the intricacies of the handling of scaled data in io.fits.

Hmm, by "little while" I think I mean "a few hours" because I'm finding some inconsistencies in how unsigned data is being handled, depending on whether you create a HDU from a numpy array with it or read it from a file.

So I wouldn't hold up the RC for this if everything else is ready.

**Comment by mwcraig** [comment]
@eteq  -- PR finally opened at https://github.com/astropy/astropy/pull/5053

**Comment by astrofrog** [comment]
@jakevdp - could you open a PR to add a short section to:

http://docs.astropy.org/en/latest/whatsnew/1.2.html#lomb-scargle-periodograms

to showcase the new lomb-scargle functionality? If you can't do it by Monday, let us know and one of us will write it. You can include a plot if you like!

**Comment by jakevdp** [comment]
@astrofrog – done in #5066. Let me know if that's what you had in mind.

**Comment by mhvk** [comment]
We should consider to get #5106 in for the real release (it corrects the definition of the Curie unit).

**Comment by eteq** [comment]
👍 to #5106, definitely a bug

**Comment by eteq** [comment]
Also, I just realized I need to write the what's new section on astrometric frames.  Will do that ASAP!

**Comment by astrofrog** [comment]
I agree https://github.com/astropy/astropy/pull/5106 needs to go in

**Comment by taldcroft** [comment]
:+1: on #5106

**Comment by taldcroft** [comment]
What about #5111 to add an IERS-specific remote timeout?  I'm a little worried that some people will have slow networks or whatever and end up getting needlessly confused.  But it is obviously not critical.

**Comment by astrofrog** [comment]
I'm fine with including #5111 - @eteq what do you think?

**Comment by astrofrog** [comment]
@eteq - everything so far is backported except #5111 

I think there have been no issues related to astropy-helpers reported, so I think I can go ahead with the final 1.2 release of the helpers, right? (and since it hasn't changed, no need to do the whole 'open a PR to check etc?)

**Comment by mhvk** [comment]
@astrofrog - I'm not sure whether this is related to astropy-helpers, or an issue with `conda`, but when I tried updating `astropy-helpers` and the template to 1.2rc1 in my `baseband` project yesterday, I got some weird travis errors (see https://travis-ci.org/mhvk/baseband/builds/138469982). In particular `NUMPY_VERSION=stable` seems to have downloaded numpy 1.5 in two occasions (and for numpy 1.9, I also get failures that weren't there before, possibly because it uses astropy 1.0.1 -- I haven't had time to investigate).

As said, though, I'm not sure this is related to astropy helpers -- and it is difficult to check since the python 3.5 tests started to fail without the update (`ConfigParser` issue).

**Comment by astrofrog** [comment]
@mhvk - don't think this is due to astropy-helpers - if anything it could be an issue with conda, and we should check what ci-helpers is doing there.

**Comment by bsipocz** [comment]
If you say "stable", then ci-helpers will install the one that comes up
from conda without any version restrictions. This worked reasonably well
until the recent changes in conda, etc.
For astropy started to fix this behaviour, but the solution is far from
being optimal, so no PR yet.

Numpy 1.9 builds are failing in many packages because of the 1.0.1 astropy
version that comes with it.

**Comment by mhvk** [comment]
@bsipocz - OK, good to hear that it is not my package only! I'm wondering if for my package at least I'm better off forgoing conda altogether, as they seem to have rather a lot of growing pains on their road to, effectively, a distribution package manager (and seem to be reinventing wheels in the process). It may be safer to just get packages from different Debian version repositories -- those are more guaranteed to not change from under me...

**Comment by astrofrog** [comment]
I don't really understand what's been happening with conda recently - it worked perfectly fine last year... But I wonder whether it would make sense to just pin conda to an old (working) version and keep it there until things have sorted themselves out.

**Comment by eteq** [comment]
:+1: on backporting #5111

**Comment by eteq** [comment]
And yes re: doing a final 1.2 release of the helpers.

**Comment by eteq** [comment]
I *think* once #5119 is in, we are ready for final release, @astrofrog!

**Comment by astrofrog** [comment]
Release done! 🎉 

Pull request to update website: https://github.com/astropy/astropy.github.com/pull/108

We should wait for the package to be updated in the default conda channel to announce

**Comment by eteq** [comment]
Since the release is done, I am closing this (but will create a new one for 1.3).  

Nice work all, especially @astrofrog for cranking through the release this time around!
