### ISSUE TITLE
Release 1.1.2 with WCSLIB 5.14 and also 1.0.9

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy#4613]
As described in https://github.com/astropy/astropy/pull/4579#issuecomment-185742656, there is a major bug in the WCSLIB bundled with Astropy 1.1 and 1.1.1 which caused #4612. This is fixed in master by https://github.com/astropy/astropy/pull/4579 but should be backported to the 1.1.x and we should then release 1.1.2, since this is a bad bug (CRVAL1 gets truncated to ~arcminute precision!).

* [x] Add regression test for #4612 
* [x] Add changelog entry
* [x] Release 1.1.2

cc @keflavich @nden @eteq

**Comment by eteq** [comment]
That sounds good to me!

**Comment by nden** [comment]
`wcslib-5.14` bundled in  #4579 also fixes #4555. There's some additional work to be done in order to propagate the flags to/from `astropy.wcs` to `wcslib`. Since it's essentially the same type of problem it would be nice to fix it now. Does anyone have time to look into this?

**Comment by eteq** [comment]
@astrofrog - I've double checked and 1.0.8 seems to show none of these precision-bouncing effects.

**Comment by astrofrog** [comment]
See https://github.com/astropy/astropy/pull/4619 for a clarification of the changelog and another regression test.

**Comment by eteq** [comment]
Note that everything that should be seems to be backported to v1.1.x now, and the only holdout is that #4561 needs to get in to restore py2.6 compatibility.

**Comment by astrofrog** [comment]
@eteq - you mean https://github.com/astropy/astropy/pull/4641 right?

**Comment by eteq** [comment]
Oops, yeah, meant #4641 (which is a fix for #4561)

**Comment by eteq** [comment]
@astrofrog - OK, I think everything is backported that should be for 1.0.x and 1.1.x.  And v1.1.x is passing: https://travis-ci.org/astropy/astropy/builds/112699046

We do need to do some changelog cleanup, though. I also think it would make sense to try to get #4650 in before a release, as it has unintended consequences beyond astropy...

**Comment by eteq** [comment]
Also now v1.0.x is passing following a changelog tweak: https://travis-ci.org/astropy/astropy/builds/112746614

**Comment by eteq** [comment]
Current TBD before release:

* [ ] Add regression test for #4650
* [ ] #4517 broke 2.6, so either get a fix in or back that out for this release
* [ ] #4657 + changing the tested numpy to 1.10 (or maybe "stable"?)
* [ ] Clean up the changelog

Note that I also changed the title to do 1.0.9 at the same time.  That will make the changelog easier anyway.

**Comment by eteq** [comment]
1.1.2 released! https://pypi.python.org/pypi/astropy/1.1.2
