### ISSUE TITLE
Wrap up the move of the sphinx build to python3

### ISSUE THREAD

**Issue by mhvk** [astropy/astropy#5246]
@bsipocz's #4556 made it possible to build the documentation well with python3, and @astrofrog and #5135 ensured this is now done on read-the-docs and by travis. But left are a few items from the checklist @astrofrog originally wrote at https://github.com/astropy/astropy/pull/4556#issuecomment-223653110

@astrofrog, @bsipocz - could you check these last items?

> I think we should do the switch to Python 3 on RTD **after** the release so that we can deal with things step by step. Note that RTD will not stop serving existing docs, so once we make the switch on RTD to Python 3, only new docs will need to be build-able. This suggests to me the following timeline:

* [X] Merge #4556 and keep Travis on Python 2.7
* [X] Go ahead with the 1.2 and 1.0.10 releases
* [X] Switch default travis build to python 3, but not yet the docs [#5155]
* [X] Switch Travis and RTD to build the docs with Python 3. At this point, new ``latest`` builds will start building with Python 3, and future 1.2.x builds will also be fine since the 1.2.x branch includes the changes here. [#5135]
* [ ] Backport any required changes for the docs to build to astropy-helpers 1.0.x, and release a new version of the helpers
* [ ] Update the 1.0.x branch of astropy core to the latest astropy-helpers and do whatever fixes are needed to get it building without errors on Python 3
* [ ] Carry out a new 1.0.x release, which will now build correctly on RTD

**Comment by bsipocz** [comment]
@mhvk - one need write access (that I don't have) to do the last 3 items, so it should wait for @astrofrog.

**Comment by astrofrog** [comment]
By the way, I realized last night that since the use of Python 3 is controlled by the YAML file not the global settings on RTD. What that means is that we could actually not backport this to the 1.0.x branch, which would save a lot of hassle.

**Comment by mhvk** [comment]
> By the way, I realized last night that since the use of Python 3 is controlled by the YAML file not the global settings on RTD. What that means is that we could actually not backport this to the 1.0.x branch, which would save a lot of hassle (and would mean we can just close this issue as-is)

So, the 1.0 docs will automatically continue to be build with python2? If so, I think we can just close this issue! So, I'll do that; feel free to reopen if needed.

**Comment by astrofrog** [comment]
> So, the 1.0 docs will automatically continue to be build with python2?

They should, yes.
