### ISSUE TITLE
HDU Improvement Checklist

### ISSUE THREAD

**Issue by saimn** [astropy/astropy#7014]
_From @embray on May 20, 2013 19:41_

This is a broad overall checklist of things that need to be fixed and cleaned up a bit in the pyfits HDU API.  Some of these reference existing issues, and some of them are new topics for which issues should be created.  I will update this checklist as I think of more items.
- [ ] Split verification into input verification and output verification phases; include support for full verification upon opening a file (see https://trac.assembla.com/pyfits/ticket/182, astropy/astropy#873, https://trac.assembla.com/pyfits/ticket/205)
- [ ] Work on a specialized ndarray subclass for FITS data that has built-in support for features like scaling and other types of transformations required for FITS data (such as 'T'/'F' -> True/False on boolean columns.  This could be used for both table columns and image arrays.
- [ ] Perhaps as sort of a specialized subclass of the above mentioned FITS data array type, support a way to decompress tile-compressed images one tile at a time. This would support something like https://trac.assembla.com/pyfits/ticket/100 and might support or supersede https://trac.assembla.com/pyfits/ticket/187)
- [x] Add a `.ver` attribute in addition to `.name` and keep `.name` and `.header['EXTNAME']` as well as `.ver` and `.header['EXTVER']` fully synchronized (see https://trac.assembla.com/pyfits/ticket/185) Should also add support for the EXTLEVEL keyword and a `.level` attribute.
- [ ] Relatedly, detect when HDUs in the same HDUList have an identical EXTNAME/EXTVER/EXTLEVEL combination.  Although the FITS standard does not forbid this but does, for obvious reasons, recommend that they be unique. So when they're not unique this should at least produce a warning.  This will be easier to tackle when #14 is implemented.
- [ ] Streamline handling of mandatory/reserved keywords on standard HDU types.  Each HDU type should have perhaps as one or more class-level attributes a set of all its reserved keywords and specify the constraints on those keywords.  This would be similar to what is already specified in each HDU type's `._verify` but made more declarative.
- [ ] It might be nice if all valid HDUs had a `.dtype` attribute returning Numpy `dtype` object specifying what the type of the data array would be even if the data hasn't been read (this might also allow an iterable of dtypes to support tables though it's not clear yet whether or not multi-field dtypes will be sufficient for this purpose)

_Copied from original issue: spacetelescope/PyFITS#13_

**Comment by saimn** [comment]
_From @embray on November 8, 2013 18:11_

Although a little of this has been implemented in v3.2 the rest of this checklist should be postponed.

**Comment by MSeifert04** [comment]
> Add a .ver attribute in addition to .name and keep .name and .header['EXTNAME'] as well as .ver and .header['EXTVER'] fully synchronized (see https://trac.assembla.com/pyfits/ticket/185) Should also add support for the EXTLEVEL keyword and a .level attribute.

Not sure if this is fully sync'd and is EXTLEVEL really supported? Sorry for not investigating this myself but I'm a bit short on time currently.

**Comment by saimn** [comment]
No idea about EXTLEVEL, all this need to be checked but I moved it here since it contains useful ideas.
