### ISSUE TITLE
Quantity.__array_function__ follow up for Quantity

### ISSUE THREAD

**Issue by mhvk** [astropy/astropy#8825]
EDIT: non-Quantity discussion of `__array_function__` is in #8610

In the non-yet-merged but ready-for-review #8808, support for numpy's `__array_function__` is introduced. For a number of functions, a decision still needs to be made, mostly on whether to stick exactly to the numpy docstring or to make adjustments to parameter defaults that make the function more useful for `Quantity`
- [X] `np.isclose`, `np.allclose`: these were never all that useful since internally they calculate `abs(a - b) < atol + rtol * abs(a)` and `atol` is given as a small number, which is interpreted as dimensionless. For `Quantity`, we could either set it to `0` or assume the units of `a`, but in either case it would become inconsistent with the docstring that users actually see. (Decision: units of `a` - #9463)
- [X] `np.broadcast_arrays` and `np.broadcast_to` by default return plain arrays, needing `subok=True` to work for `Quantity`. We could change the default if a `Quantity` is present. Again, the possible issue is that the docstring will no longer be correct. (Decision: leave as is, since old code could cease working; #9463)

Furthermore, a few top-level functions need an actual implementation and/or better test cases:
- [X] `np.histogram2d` and `np.histogramdd` (see #8900)
- [X] `np.piecewise` (see #8884)
- [X] `np.apply_along_axis` and `np.apply_over_axis` (see #8900) 
- [X] The setops functions such as `np.unique` might as well be supported (see #8900)

And finally we should also cover the numpy submodules that have routines not exported to the top level. In particular:
- [X] `np.fft` (#9464)
- [X] `np.linalg` (see issue #8622; PR #9494)
- [X] `np.polynomial` (has no functions that can be overridden).

EDIT: And it would probably be good to add tests for `Quantity` subclasses:
- [ ] `LogQuantity` such as `Magnitude`
- [ ] `Angle`s such as `Longitude`

**Comment by StanczakDominik** [comment]
This is probably the best place to report this: on our PlasmaPy travis branch running numpy dev and astropy dev, `np.unique` on Quantities is now failing due to `__array__function`:

```
E   TypeError: no implementation found for 'numpy.unique' on types that implement __array_function__: [<class 'astropy.units.quantity.Quantity'>]
```

See https://travis-ci.org/PlasmaPy/PlasmaPy/jobs/548606577#L1113 for souce.

**Comment by mhvk** [comment]
@StanczakDominik - yes, definitely the right place. I didn't think that the `setops` functions would be used with `Quantity` given that they are floats, but clearly I was wrong! Especially ones that just worked before should be easy to add back.

**Comment by mhvk** [comment]
@StanczakDominik - see #8900 for a fix.

**Comment by mhvk** [comment]
p.s. I think `np.unique` did not work correctly when one passed in an `axis` argument, so the new version doesn't just fix a regression, but makes it better as well.

**Comment by StanczakDominik** [comment]
Wow, that was quick, thanks! I looked over #8900 and understood literally nothing of it - I suppose I'll need to finally catch up on NEP-18.

**Comment by mhvk** [comment]
@StanczakDominik - you not understanding is not a good sign... The basic idea is that `__array_function__` can be used to just replace a numpy implementation. But in our case, we generally transform ourselves into arrays, taking proper care of the units, then call the numpy implementation with those pure arrays, and finally add a unit back if needed.

**Comment by StanczakDominik** [comment]
Ah, that clears things up, then! I didn't connect what you were doing there to the the `__array_function__` protocol as I understood it, but I didn't realize there was no connection - you actually were doing stuff on top of that, which is a neat idea.

**Comment by bsipocz** [comment]
@mhvk - I'm removing the milestone from here as there are no more open PRs ready for 4.0 that are related.

**Comment by mhvk** [comment]
Since this is mostly done, closing - leftovers at #10575.
