### ISSUE TITLE
Remove deprecated functionality for 4.0 release

### ISSUE THREAD

**Issue by pllim** [astropy/astropy#8888]
As discussed on Slack, this issue is to track the **removal** of deprecated stuff for `astropy` 4.0 LTS release. Update this as needed. I added cc for people who brought it up or implemented the deprecation or would be the most interested in its future, but all are welcome to have a look.

Disclaimer: I found the following using a simple grep for "deprecate". If I missed something, feel free to add to the list.

**Candidates for removal**

(Listing more or less in the alphabetical order of the affected sub-package. Check the box if removal is done and xref the relevant PRs.)

* Remove `io.ascii` Reader/Writer and unified I/O interfaces; see #8567 -- cc @taldcroft (UPDATE: Pushed back due to lack of time)
- [x] Remove deprecated keyword in `convolve.py`, which was done in 2.0 release in #5782 -- cc @keflavich See #9356 
- [x] Remove deprecated parameter from `Gaussian2DKernel`, which was done in 3.0 release in #6748 -- cc @adamginsburg See #9356
- Remove `representation` keyword in coordinates `baseframe.py`, which was deprecated in 3.1 release in #8119 -- cc @eteq _EDIT: this was punted to a future LTS release_
- [x] Remove deprecated arguments in `galactocentric.py`, which was done in 2.0 release in #6219 -- cc @adrn Removed in #9326
- [x] Remove `latitude` and `longitude` in `earth.py`, which was deprecated in 2.0 release in #6237 -- cc @eteq Removed in #9326
- [X] Remove `recommended_units` in `representations.py`, which was deprecated in 3.0 release in #6858 -- cc @mhvk (#8892)
- [x] Remove `compatibility_mode` in `hdf5.py`, which was deprecated in 3.0 release in #6304 -- cc @matteobachetti Done in #8899
- [x] Remove `usecPickle` in `pickle_helpers.py`, which was deprecated in 3.0 release in #6655 -- cc @bsipocz. Removed in #8890 
- [x] Remove `rotation_matrix_from_angle` method in `rotations.py`, which was deprecated in 2.0 release in #6235 -- @nden Removed in #9369
- [x] Remove `deprecated_renamed_argument` from `biweight.py`, which was added in 2.0 release in #5991 -- @larrybradley.  Removed in #8948.
- [x] Remove `deprecated_renamed_argument` from `stats/funcs.py`, which was added in 2.0 release in #5232 -- cc @keflavich.  Removed in #9011.
- [x] Remove `deprecated_renamed_argument` from `sigma_clipping.py`, which was added in 3.1 release in #7478 -- cc @larrybradley.  Removed in #8948.
- [X] Remove `magnitude_zero_points.py`, which was deprecated in 3.1 release in #7891 -- see #9353
- [x] Remove `funcsigs.py` and `futures`, which were deprecated in 3.0 release in #6598 -- cc @saimn. Done in  #8909 
- [x] Remove `utils.compat.numpy` modules that were deprecated in 3.0 release in #6691 -- cc @MSeifert04 Done in #8910
- [x] Remove `_naxis1` and `_naxis2` from `wcs.py`, which were deprecated in 3.1 in #7973 -- cc @nden Removed in #9465.
- [x] Remove bundled `six`, which is not needed after 3.0 release -- PR by @saimn waiting at #8315, see https://github.com/astropy/astropy/issues/8888#issuecomment-504146773

**Need clarification**

* Deprecate representation, remove `_normalize_representation_type`; see #8886 -- cc @adrn _EDIT: this was clarified in #9320_

**Decide to keep for now**

* Anything related to `io.fits` 😬 
* Anything in `extern`; Looking at you, `jsquery` and `configobj`.
* Deprecated `stats.bls` and `stats.lombscargle` namespace, which was moved in 3.2 in #8599 -- https://github.com/astropy/astropy/issues/8888#issuecomment-504137880

**Comment by bsipocz** [comment]
> Remove deprecated stats.bls and stats.lombscargle namespace, which was moved in 3.2 in #8599 

this is too soon, anecdotally we know that many people are using LS from astropy both in astronomy and beyond.

**Comment by bsipocz** [comment]
@pllim - we also need to remove six, that's in extern and the PR is already been waiting for the merge button to be pushed (but first we rather make sure again that none of the coordinated packages, etc are using it in their latest releases...).

**Comment by mhvk** [comment]
A very lucky number to remove cruft!

Aside: previously, it seems we never added entries to the changelog for removals of deprecated features. Should we?

**Comment by bsipocz** [comment]
We did, usually under API change, or other changes, starting with the word "Removed".

**Comment by bsipocz** [comment]
@nden - Do you think the deprecations listed above could be removed from modeling and wcs? If yes, I'm happy to go ahead and open PRs for them, otherwise we can remove them from the list.

**Comment by pllim** [comment]
@bsipocz , I think we done here! If you agree, please close the issue. 😄

**Comment by bsipocz** [comment]
I found this issue super helpful to keep track of stuff we needed to clean up, and vote for having similar ones for new releases, or at least for the new LTS releases, too.

**Comment by mhvk** [comment]
Indeed, this was super helpful, thanks @pllim!
